############################
# @author Elias De Hondt   #
# @see https://eliasdh.com #
# @since 24/11/2024        #
############################
---
apiVersion: v1
kind: ClusterConfiguration
metadata:
  name: cluster02
controlPlaneEndpoint: "192.168.1.170:6443"
networking:
  podSubnet: "10.244.0.0/16"
criSocket: "/run/containerd/containerd.sock"
---