############################
# @author Elias De Hondt   #
# @see https://eliasdh.com #
# @since 24/11/2024        #
############################
---
apiVersion: v1
kind: Namespace
metadata:
  name: proxyserver002
  labels:
    name: proxyserver002
    app: proxyserver002
    owner: EliasDH
    environment: production
  annotations:
    description: This namespace is used for the proxyserver002 application.
    contact: info@eliasdh.com
---