############################
# @author Elias De Hondt   #
# @see https://eliasdh.com #
# @since 24/11/2024        #
############################
---
apiVersion: v1
kind: Service
metadata:
  name: proxyserver002-service
  namespace: proxyserver002
spec:
  type: ExternalName
  externalName: 192.168.1.103
  ports:
  - port: 80
    targetPort: 80
---