############################
# @author Elias De Hondt   #
# @see https://eliasdh.com #
# @since 24/11/2024        #
############################
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: webserver004-letsencrypt-issuer
  namespace: webserver004
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: elias.dehondt@outlook.com
    privateKeySecretRef:
      name: webserver004-letsencrypt-issuer-key
    solvers:
      - http01:
          ingress:
            ingressClassName: nginx
---