############################
# @author Elias De Hondt   #
# @see https://eliasdh.com #
# @since 24/11/2024        #
############################
---
apiVersion: v1
kind: Service
metadata:
  name: sshserver001-service
  namespace: sshserver001
spec:
  selector:
    app: sshserver001
  ports:
    - protocol: TCP
      port: 22
      targetPort: 2222
  type: LoadBalancer
---