############################
# @author Elias De Hondt   #
# @see https://eliasdh.com #
# @since 24/11/2024        #
############################
# kubectl apply -f Secret.yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-root-password
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: MTIz # 123
---