############################
# @author Elias De Hondt   #
# @see https://eliasdh.com #
# @since 24/11/2024        #
############################
---
# For PiHole
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole1-pvc
  namespace: pihole
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
---
# For DNSMasq
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole2-pvc
  namespace: pihole
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
---