############################
# @author Elias De Hondt   #
# @see https://eliasdh.com #
# @since 24/11/2024        #
############################
# kubectl apply -f Ingress.yaml
# kubectl get ingress -n test-web-app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: test-web-app
  annotations:
    nginx.ingress.kubernetes.io/ingress.class: "nginx"
spec:
  ingressClassName: nginx
  rules:
    - host: test-web-app.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: test-web-app-service
                port:
                  number: 80
---