############################
# @author Elias De Hondt   #
# @see https://eliasdh.com #
# @since 24/11/2024        #
############################
---
apiVersion: v1
kind: Namespace
metadata:
  name: test-web-app
  labels:
    name: test-web-app
    app: test-web-app
    owner: EliasDH
    environment: production
---