############################
# @author Elias De Hondt   #
# @see https://eliasdh.com #
# @since 24/11/2024        #
############################
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxyserver1-keepalived-deployment
  namespace: proxyserver1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxyserver1-keepalived-deployment
  template:
    metadata:
      labels:
        app: proxyserver1-keepalived-deployment
    spec:
      containers:
        - name: proxyserver1-keepalived-container
          image: osixia/keepalived:latest
          volumeMounts:
            - name: proxyserver1-keepalived-config
              mountPath: /etc/keepalived/keepalived.conf
              subPath: keepalived.conf
      volumes:
        - name: proxyserver1-keepalived-config
          configMap:
            name: proxyserver1-keepalived-config
---