############################
# @author Elias De Hondt   #
# @see https://eliasdh.com #
# @since 24/11/2024        #
############################
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
metadata:
  name: cluster03
controlPlaneEndpoint: "10.3.0.10:6443"
networking:
  podSubnet: "10.244.0.0/16"
criSocket: "/run/containerd/containerd.sock"
---