############################
# @author Elias De Hondt   #
# @see https://eliasdh.com #
# @since 24/11/2024        #
############################
---
# This is the default address pool. 
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: address-pool-1
  namespace: metallb-system
spec:
  addresses:
    - 192.168.1.200-192.168.1.250 # 50 addresses.
---
# This is a static IP address for the proxy that is used for accessing the master nodes.
# apiVersion: metallb.io/v1beta1
# kind: IPAddressPool
# metadata:
#   name: static-ip-1
#   namespace: metallb-system
# spec:
#   addresses:
#     - 192.168.1.170/32 # 1 address.
# ---