############################
# @author Elias De Hondt   #
# @see https://eliasdh.com #
# @since 24/11/2024        #
############################
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: address-pool-1
  namespace: metallb-system
spec:
  addresses:
    - 192.168.1.160-192.168.1.169
---