############################
# @author Elias De Hondt   #
# @see https://eliasdh.com #
# @since 24/11/2024        #
############################
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver003-deployment
  namespace: webserver003
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webserver003
  template:
    metadata:
      labels:
        app: webserver003
    spec:
      containers:
        - name: webserver003-container
          image: "ghcr.io/eliasdh-com/levelupbe-frontend:latest"
          ports:
          - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---