############################
# @author Elias De Hondt   #
# @see https://eliasdh.com #
# @since 24/11/2024        #
############################
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-root-password
  namespace: mysql
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: MTIz # 123
---