############################
# @author Elias De Hondt   #
# @see https://eliasdh.com #
# @since 24/11/2024        #
############################
name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-yaml:
    name: Lint YAML Files
    runs-on: ubuntu-latest

    steps:
      # Step 1
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2
      - name: Lint YAML Files
        uses: github/super-linter@v5
        with:
          entryPoint: "yaml"
        env:
          LINTER_RULES_PATH: ".github/linters"

  validate-yaml:
    name: Validate Kubernetes Manifests
    runs-on: ubuntu-latest
    needs: lint-yaml

    steps:
      # Step 1
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2
      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.28.0'

      # Step 3
      - name: Validate Kubernetes YAML
        run: |
          # Test all YAML files under 'Supercluster/' for syntax errors
          for file in $(find supercluster -name '*.yaml'); do
            echo "Validating $file"
            kubectl apply --dry-run=client -f $file
          done